import React from 'react';
import * as XLSX from 'xlsx';

const COMBINATIONS_B = ['q123','q124','q134','q234','q12','q13','q14','q23','q24','q34','q1','q2','q3','q4','none'];

const SectionBModals = ({
  sectionBRows,
  sectionBObtainedRows,
  showSectionBGeneratedModal,
  setShowSectionBGeneratedModal,
  showSectionBObtainedModal,
  setShowSectionBObtainedModal,
  getAutoGeneratedCombinationB,
  calculateSectionBCOMsrd,
  calculateUnitVB,
  calculateCombinationRatioB,
  calculateTotalCOMsrdB,
  calculateStDevPB,
  calculateDistB,
  getStudentCOTotalB,
  getStudentQuestionTotalB,
  getStudentZeroCountB,
  getStudentAnswerCombinationB,
  getStudentCODistributionB,
  formatNumber,
}) => {
  const modalOverlayStyle = {
    position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000
  };
  const modalBoxStyle = {
    backgroundColor: 'white', padding: '20px', borderRadius: '16px',
    maxWidth: '90%', maxHeight: '90%', overflow: 'auto', position: 'relative'
  };
  const closeBtnStyle = {
    padding: '4px 8px', backgroundColor: '#e74c3c', color: 'white',
    border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '12px'
  };

  const handleExportToExcel = () => {
    const wb = XLSX.utils.book_new();

    // Sheet 1: Obtained Marks for Section-B
    const fields = ['Q1a','Q1b','Q1c','Q1d','Q2a','Q2b','Q2c','Q2d','Q3a','Q3b','Q3c','Q3d','Q4a','Q4b','Q4c','Q4d'];
    const header1 = ['Roll','5(a)','5(b)','5(c)','5(d)','6(a)','6(b)','6(c)','6(d)','7(a)','7(b)','7(c)','7(d)','8(a)','8(b)','8(c)','8(d)','Total'];
    const data1 = sectionBObtainedRows.map(row => {
      const total = fields.reduce((sum, f) => sum + (parseFloat(row[f]) || 0), 0);
      return [row.rollNumber || '-', ...fields.map(f => parseFloat(row[f]) || 0), total];
    });
    const ws1 = XLSX.utils.aoa_to_sheet([header1, ...data1]);
    XLSX.utils.book_append_sheet(wb, ws1, 'Obtained Marks - Section B');

    // Sheet 2: Student Analysis
    const coHeaders = sectionBRows.map(r => r.coNumber);
    const header2 = ['Roll', ...coHeaders, 'Q 5', 'Q 6', 'Q 7', 'Q 8', 'Zero Count', 'Ans Combination', ...coHeaders.map(c => `${c} (Dist)`), 'Total'];
    const data2 = sectionBObtainedRows.map(studentRow => {
      const coTotals = sectionBRows.map(coRow => parseFloat(formatNumber(getStudentCOTotalB(studentRow, coRow.coNumber))) || 0);
      const qTotals = [1,2,3,4].map(q => parseFloat(formatNumber(getStudentQuestionTotalB(studentRow, q))) || 0);
      const zeroCnt = getStudentZeroCountB(studentRow);
      const ansComb = getStudentAnswerCombinationB(studentRow);
      const coDists = sectionBRows.map(coRow => parseFloat(formatNumber(getStudentCODistributionB(studentRow, coRow.coNumber))) || 0);
      const total = parseFloat(formatNumber(coDists.reduce((s, v) => s + v, 0))) || 0;
      return [studentRow.rollNumber || '-', ...coTotals, ...qTotals, zeroCnt, ansComb, ...coDists, total];
    });
    const ws2 = XLSX.utils.aoa_to_sheet([header2, ...data2]);
    XLSX.utils.book_append_sheet(wb, ws2, 'Student Analysis');

    XLSX.writeFile(wb, 'SectionB_Marks.xlsx');
  };

  return (
    <>
      {/* Section B Generated Table Modal */}
      {showSectionBGeneratedModal && (
        <div style={modalOverlayStyle}>
          <div style={modalBoxStyle}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <h3>Generated Table - Section B Possible Answer Combinations</h3>
              <button onClick={() => setShowSectionBGeneratedModal(false)} style={closeBtnStyle}>✕</button>
            </div>
            <div className="table-wrapper">
              <table className="section-a-table">
                <thead>
                  <tr>
                    <th rowSpan="2">CO No.</th>
                    <th colSpan="15">Possible ans comb.</th>
                    <th rowSpan="2">CO msrd</th>
                    <th rowSpan="2">Unit V</th>
                    <th rowSpan="2">(5,6,7)</th>
                    <th rowSpan="2">(5,6,8)</th>
                    <th rowSpan="2">(5,7,8)</th>
                    <th rowSpan="2">(6,7,8)</th>
                  </tr>
                  <tr>
                    <th>5,6,7</th><th>5,6,8</th><th>5,7,8</th><th>6,7,8</th>
                    <th>5,6</th><th>5,7</th><th>5,8</th><th>6,7</th><th>6,8</th><th>7,8</th>
                    <th>5</th><th>6</th><th>7</th><th>8</th><th>None</th>
                  </tr>
                </thead>
                <tbody>
                  {sectionBRows.map((row, idx) => (
                    <tr key={row.coNumber || idx}>
                      <td className="co-label">{row.coNumber || '-'}</td>
                      {COMBINATIONS_B.map(comb => (
                        <td key={comb} style={{ backgroundColor: '#f8f9fa' }}>
                          {getAutoGeneratedCombinationB(row, comb)}
                        </td>
                      ))}
                      <td style={{ backgroundColor: '#f8f9fa', fontWeight: 'bold' }}>
                        {calculateSectionBCOMsrd(row)}
                      </td>
                      <td style={{ backgroundColor: '#f8f9fa' }}>{formatNumber(calculateUnitVB(row))}</td>
                      {['q123','q124','q134','q234'].map(comb => (
                        <td key={comb} style={{ backgroundColor: '#fff3cd' }}>
                          {formatNumber(calculateCombinationRatioB(row, comb))}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr>
                    <td className="footer-label">Total</td>
                    {COMBINATIONS_B.map(comb => (
                      <td key={comb} style={{ textAlign: 'center', fontWeight: 'bold' }}>
                        {sectionBRows.reduce((sum, row) => sum + getAutoGeneratedCombinationB(row, comb), 0)}
                      </td>
                    ))}
                    <td style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#f8f9fa' }}>
                      {calculateTotalCOMsrdB()}
                    </td>
                    <td style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#f8f9fa' }}>
                      {formatNumber(sectionBRows.reduce((sum, row) => sum + calculateUnitVB(row), 0))}
                    </td>
                    {['q123','q124','q134','q234'].map(comb => (
                      <td key={comb} style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#fff3cd' }}>
                        {formatNumber(sectionBRows.reduce((sum, row) => sum + calculateCombinationRatioB(row, comb), 0))}
                      </td>
                    ))}
                  </tr>
                  <tr>
                    <td colSpan="16" style={{ textAlign: 'center', border: 'none' }}></td>
                    <td className="footer-label" colSpan="2" style={{ textAlign: 'center' }}>StDev</td>
                    {['q123','q124','q134','q234'].map(comb => (
                      <td key={comb} style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#ecfdf5' }}>
                        {formatNumber(calculateStDevPB(comb))}
                      </td>
                    ))}
                  </tr>
                  <tr style={{ borderTop: 'none' }}>
                    <td colSpan="16" style={{ textAlign: 'center', border: 'none' }}></td>
                    <td className="footer-label" colSpan="2" style={{ textAlign: 'center', borderTop: 'none' }}>Dist</td>
                    {['q123','q124','q134','q234'].map(comb => (
                      <td key={comb} style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#ecfdf5', borderTop: 'none' }}>
                        {formatNumber(Math.sqrt(calculateDistB(comb)))}
                      </td>
                    ))}
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Section B Obtained Generated Table Modal */}
      {showSectionBObtainedModal && (
        <div style={modalOverlayStyle}>
          <div style={modalBoxStyle}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <h3>Generated Table - Student Analysis (Section B)</h3>
              <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                <button
                  onClick={handleExportToExcel}
                  style={{ padding: '6px 14px', backgroundColor: '#27ae60', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '13px', fontWeight: '600' }}
                  title="Export Obtained Marks and Student Analysis to Excel"
                >
                  ⬇ Export Excel
                </button>
                <button onClick={() => setShowSectionBObtainedModal(false)} style={closeBtnStyle}>✕</button>
              </div>
            </div>
            <div className="table-wrapper">
              <table className="section-a-table">
                <thead>
                  <tr>
                    <th rowSpan="2">Roll</th>
                    <th colSpan={sectionBRows.length}>Total Marks Obtained Per CO</th>
                    <th colSpan="4">Q No.</th>
                    <th rowSpan="2">Zero Count</th>
                    <th rowSpan="2">Ans Combination</th>
                    <th colSpan={sectionBRows.length}>CO Marks Distribution Per Student</th>
                    <th rowSpan="2">Total</th>
                  </tr>
                  <tr>
                    {sectionBRows.map((row, idx) => (<th key={`co-h-${idx}`}>{row.coNumber}</th>))}
                    <th>5</th><th>6</th><th>7</th><th>8</th>
                    {sectionBRows.map((row, idx) => (<th key={`co-dh-${idx}`}>{row.coNumber}</th>))}
                  </tr>
                </thead>
                <tbody>
                  {sectionBObtainedRows.length > 0 ? sectionBObtainedRows.map((studentRow, idx) => (
                    <tr key={`sectB-co-${studentRow.rollNumber}-${idx}`}>
                      <td className="roll-cell" title={studentRow.name || studentRow.rollNumber}>
                        {studentRow.rollNumber || '-'}
                      </td>
                      {sectionBRows.map((coRow, coIdx) => (
                        <td key={`co-t-${coIdx}`} style={{ textAlign: 'center', backgroundColor: '#f8f9fa' }}>
                          {formatNumber(getStudentCOTotalB(studentRow, coRow.coNumber))}
                        </td>
                      ))}
                      {[1,2,3,4].map(q => (
                        <td key={q} style={{ textAlign: 'center', backgroundColor: '#ecfdf5' }}>
                          {formatNumber(getStudentQuestionTotalB(studentRow, q))}
                        </td>
                      ))}
                      <td style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#fff3cd' }}>
                        {getStudentZeroCountB(studentRow)}
                      </td>
                      <td style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#d4edda' }}>
                        {getStudentAnswerCombinationB(studentRow)}
                      </td>
                      {sectionBRows.map((coRow, coIdx) => (
                        <td key={`co-d-${coIdx}`} style={{ textAlign: 'center', backgroundColor: '#f8f9fa' }}>
                          {formatNumber(getStudentCODistributionB(studentRow, coRow.coNumber))}
                        </td>
                      ))}
                      <td style={{ textAlign: 'center', fontWeight: 'bold' }}>
                        {formatNumber(sectionBRows.reduce((sum, coRow) => sum + getStudentCODistributionB(studentRow, coRow.coNumber), 0))}
                      </td>
                    </tr>
                  )) : (
                    <tr>
                      <td colSpan={3 + sectionBRows.length * 2 + 6} style={{ textAlign: 'center', padding: '20px', color: '#7f8c8d' }}>
                        No student data available.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default SectionBModals;
