import React from 'react';
import * as XLSX from 'xlsx';

const COMBINATIONS = ['q123','q124','q134','q234','q12','q13','q14','q23','q24','q34','q1','q2','q3','q4','none'];

const SectionAModals = ({
  sectionARows,
  sectionAObtainedRows,
  showSectionAGeneratedModal,
  setShowSectionAGeneratedModal,
  showSectionAObtainedModal,
  setShowSectionAObtainedModal,
  getAutoGeneratedCombination,
  calculateSectionACOMsrd,
  calculateUnitV,
  calculateCombinationRatio,
  calculateTotalCOMsrd,
  calculateStDevP,
  calculateDist,
  getStudentCOTotal,
  getStudentQuestionTotal,
  getStudentZeroCount,
  getStudentAnswerCombination,
  getStudentCODistribution,
  formatNumber,
}) => {
  const modalOverlayStyle = {
    position: 'fixed', top: 0, left: 0, right: 0, bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000
  };
  const modalBoxStyle = {
    backgroundColor: 'white', padding: '20px', borderRadius: '16px',
    maxWidth: '90%', maxHeight: '90%', overflow: 'auto', position: 'relative'
  };
  const closeBtnStyle = {
    padding: '4px 8px', backgroundColor: '#e74c3c', color: 'white',
    border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '12px'
  };

  const handleExportToExcel = () => {
    const wb = XLSX.utils.book_new();

    // Sheet 1: Obtained Marks for Section-A
    const fields = ['Q1a','Q1b','Q1c','Q1d','Q2a','Q2b','Q2c','Q2d','Q3a','Q3b','Q3c','Q3d','Q4a','Q4b','Q4c','Q4d'];
    const header1 = ['Roll','1(a)','1(b)','1(c)','1(d)','2(a)','2(b)','2(c)','2(d)','3(a)','3(b)','3(c)','3(d)','4(a)','4(b)','4(c)','4(d)','Total'];
    const data1 = sectionAObtainedRows.map(row => {
      const total = fields.reduce((sum, f) => sum + (parseFloat(row[f]) || 0), 0);
      return [row.rollNumber || '-', ...fields.map(f => parseFloat(row[f]) || 0), total];
    });
    const ws1 = XLSX.utils.aoa_to_sheet([header1, ...data1]);
    XLSX.utils.book_append_sheet(wb, ws1, 'Obtained Marks - Section A');

    // Sheet 2: Student Analysis
    const coHeaders = sectionARows.map(r => r.coNumber);
    const header2 = ['Roll', ...coHeaders, 'Q 1', 'Q 2', 'Q 3', 'Q 4', 'Zero Count', 'Ans Combination', ...coHeaders.map(c => `${c} (Dist)`), 'Total'];
    const data2 = sectionAObtainedRows.map(studentRow => {
      const coTotals = sectionARows.map(coRow => parseFloat(formatNumber(getStudentCOTotal(studentRow, coRow.coNumber))) || 0);
      const qTotals = [1,2,3,4].map(q => parseFloat(formatNumber(getStudentQuestionTotal(studentRow, q))) || 0);
      const zeroCnt = getStudentZeroCount(studentRow);
      const ansComb = getStudentAnswerCombination(studentRow);
      const coDists = sectionARows.map(coRow => parseFloat(formatNumber(getStudentCODistribution(studentRow, coRow.coNumber))) || 0);
      const total = parseFloat(formatNumber(coDists.reduce((s, v) => s + v, 0))) || 0;
      return [studentRow.rollNumber || '-', ...coTotals, ...qTotals, zeroCnt, ansComb, ...coDists, total];
    });
    const ws2 = XLSX.utils.aoa_to_sheet([header2, ...data2]);
    XLSX.utils.book_append_sheet(wb, ws2, 'Student Analysis');

    XLSX.writeFile(wb, 'SectionA_Marks.xlsx');
  };

  return (
    <>
      {/* Section A Generated Table Modal */}
      {showSectionAGeneratedModal && (
        <div style={modalOverlayStyle}>
          <div style={modalBoxStyle}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <h3>Generated Table - Section A Possible Answer Combinations</h3>
              <button onClick={() => setShowSectionAGeneratedModal(false)} style={closeBtnStyle}>✕</button>
            </div>
            <div className="table-wrapper">
              <table className="section-a-table">
                <thead>
                  <tr>
                    <th rowSpan="2">CO No.</th>
                    <th colSpan="15">Possible ans comb.</th>
                    <th rowSpan="2">CO msrd</th>
                    <th rowSpan="2">Unit V</th>
                    <th rowSpan="2">(1,2,3)</th>
                    <th rowSpan="2">(1,2,4)</th>
                    <th rowSpan="2">(1,3,4)</th>
                    <th rowSpan="2">(2,3,4)</th>
                  </tr>
                  <tr>
                    <th>1,2,3</th><th>1,2,4</th><th>1,3,4</th><th>2,3,4</th>
                    <th>1,2</th><th>1,3</th><th>1,4</th><th>2,3</th><th>2,4</th><th>3,4</th>
                    <th>1</th><th>2</th><th>3</th><th>4</th><th>None</th>
                  </tr>
                </thead>
                <tbody>
                  {sectionARows.map((row, idx) => (
                    <tr key={row.coNumber || idx}>
                      <td className="co-label">{row.coNumber || '-'}</td>
                      {COMBINATIONS.map(comb => (
                        <td key={comb} style={{ backgroundColor: '#f8f9fa' }}>
                          {getAutoGeneratedCombination(row, comb)}
                        </td>
                      ))}
                      <td style={{ backgroundColor: '#f8f9fa', fontWeight: 'bold' }}>
                        {calculateSectionACOMsrd(row)}
                      </td>
                      <td style={{ backgroundColor: '#f8f9fa' }}>{formatNumber(calculateUnitV(row))}</td>
                      {['q123','q124','q134','q234'].map(comb => (
                        <td key={comb} style={{ backgroundColor: '#fff3cd' }}>
                          {formatNumber(calculateCombinationRatio(row, comb))}
                        </td>
                      ))}
                    </tr>
                  ))}
                </tbody>
                <tfoot>
                  <tr>
                    <td className="footer-label">Total</td>
                    {COMBINATIONS.map(comb => (
                      <td key={comb} style={{ textAlign: 'center', fontWeight: 'bold' }}>
                        {sectionARows.reduce((sum, row) => sum + getAutoGeneratedCombination(row, comb), 0)}
                      </td>
                    ))}
                    <td style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#f8f9fa' }}>
                      {calculateTotalCOMsrd()}
                    </td>
                    <td style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#f8f9fa' }}>
                      {formatNumber(sectionARows.reduce((sum, row) => sum + calculateUnitV(row), 0))}
                    </td>
                    {['q123','q124','q134','q234'].map(comb => (
                      <td key={comb} style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#fff3cd' }}>
                        {formatNumber(sectionARows.reduce((sum, row) => sum + calculateCombinationRatio(row, comb), 0))}
                      </td>
                    ))}
                  </tr>
                  <tr>
                    <td colSpan="16" style={{ textAlign: 'center', border: 'none' }}></td>
                    <td className="footer-label" colSpan="2" style={{ textAlign: 'center' }}>StDev</td>
                    {['q123','q124','q134','q234'].map(comb => (
                      <td key={comb} style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#ecfdf5' }}>
                        {formatNumber(calculateStDevP(comb))}
                      </td>
                    ))}
                  </tr>
                  <tr style={{ borderTop: 'none' }}>
                    <td colSpan="16" style={{ textAlign: 'center', border: 'none' }}></td>
                    <td className="footer-label" colSpan="2" style={{ textAlign: 'center', borderTop: 'none' }}>Dist</td>
                    {['q123','q124','q134','q234'].map(comb => (
                      <td key={comb} style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#ecfdf5', borderTop: 'none' }}>
                        {formatNumber(Math.sqrt(calculateDist(comb)))}
                      </td>
                    ))}
                  </tr>
                </tfoot>
              </table>
            </div>
          </div>
        </div>
      )}

      {/* Section A Obtained Generated Table Modal */}
      {showSectionAObtainedModal && (
        <div style={modalOverlayStyle}>
          <div style={modalBoxStyle}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
              <h3>Generated Table - Student Analysis</h3>
              <div style={{ display: 'flex', gap: '8px', alignItems: 'center' }}>
                <button
                  onClick={handleExportToExcel}
                  style={{ padding: '6px 14px', backgroundColor: '#27ae60', color: 'white', border: 'none', borderRadius: '4px', cursor: 'pointer', fontSize: '13px', fontWeight: '600' }}
                  title="Export Obtained Marks and Student Analysis to Excel"
                >
                  ⬇ Export Excel
                </button>
                <button onClick={() => setShowSectionAObtainedModal(false)} style={closeBtnStyle}>✕</button>
              </div>
            </div>
            <div className="table-wrapper">
              <table className="section-a-table">
                <thead>
                  <tr>
                    <th rowSpan="2">Roll</th>
                    <th colSpan={sectionARows.length}>Total Marks Obtained Per CO</th>
                    <th colSpan="4">Q No.</th>
                    <th rowSpan="2">Zero Count</th>
                    <th rowSpan="2">Ans Combination</th>
                    <th colSpan={sectionARows.length}>CO Marks Distribution Per Student</th>
                    <th rowSpan="2">Total</th>
                  </tr>
                  <tr>
                    {sectionARows.map((row, idx) => (<th key={`co-h-${idx}`}>{row.coNumber}</th>))}
                    <th>1</th><th>2</th><th>3</th><th>4</th>
                    {sectionARows.map((row, idx) => (<th key={`co-dh-${idx}`}>{row.coNumber}</th>))}
                  </tr>
                </thead>
                <tbody>
                  {sectionAObtainedRows.length > 0 ? sectionAObtainedRows.map((studentRow, idx) => (
                    <tr key={`sectA-co-${studentRow.rollNumber}-${idx}`}>
                      <td className="roll-cell" title={studentRow.name || studentRow.rollNumber}>
                        {studentRow.rollNumber || '-'}
                      </td>
                      {sectionARows.map((coRow, coIdx) => (
                        <td key={`co-t-${coIdx}`} style={{ textAlign: 'center', backgroundColor: '#f8f9fa' }}>
                          {formatNumber(getStudentCOTotal(studentRow, coRow.coNumber))}
                        </td>
                      ))}
                      {[1,2,3,4].map(q => (
                        <td key={q} style={{ textAlign: 'center', backgroundColor: '#ecfdf5' }}>
                          {formatNumber(getStudentQuestionTotal(studentRow, q))}
                        </td>
                      ))}
                      <td style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#fff3cd' }}>
                        {getStudentZeroCount(studentRow)}
                      </td>
                      <td style={{ textAlign: 'center', fontWeight: 'bold', backgroundColor: '#d4edda' }}>
                        {getStudentAnswerCombination(studentRow)}
                      </td>
                      {sectionARows.map((coRow, coIdx) => (
                        <td key={`co-d-${coIdx}`} style={{ textAlign: 'center', backgroundColor: '#f8f9fa' }}>
                          {formatNumber(getStudentCODistribution(studentRow, coRow.coNumber))}
                        </td>
                      ))}
                      <td style={{ textAlign: 'center', fontWeight: 'bold' }}>
                        {formatNumber(sectionARows.reduce((sum, coRow) => sum + getStudentCODistribution(studentRow, coRow.coNumber), 0))}
                      </td>
                    </tr>
                  )) : (
                    <tr>
                      <td colSpan={3 + sectionARows.length * 2 + 6} style={{ textAlign: 'center', padding: '20px', color: '#7f8c8d' }}>
                        No student data available.
                      </td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </>
  );
};

export default SectionAModals;
